name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build da imagem Docker
        run: docker build -t devops-app .

      - name: Rodar container (deploy)
        run: docker run devops-app
